// SPDX-License-Identifier:Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	apiv1beta1 "github.com/metallb/frr-k8s/api/v1beta1"
	versioned "github.com/metallb/frr-k8s/pkg/client/clientset/versioned"
	internalinterfaces "github.com/metallb/frr-k8s/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/metallb/frr-k8s/pkg/client/listers/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FRROperatorConfigurationInformer provides access to a shared informer and lister for
// FRROperatorConfigurations.
type FRROperatorConfigurationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.FRROperatorConfigurationLister
}

type fRROperatorConfigurationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFRROperatorConfigurationInformer constructs a new informer for FRROperatorConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFRROperatorConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFRROperatorConfigurationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFRROperatorConfigurationInformer constructs a new informer for FRROperatorConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFRROperatorConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().FRROperatorConfigurations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApiV1beta1().FRROperatorConfigurations(namespace).Watch(context.TODO(), options)
			},
		},
		&apiv1beta1.FRROperatorConfiguration{},
		resyncPeriod,
		indexers,
	)
}

func (f *fRROperatorConfigurationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFRROperatorConfigurationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *fRROperatorConfigurationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiv1beta1.FRROperatorConfiguration{}, f.defaultInformer)
}

func (f *fRROperatorConfigurationInformer) Lister() v1beta1.FRROperatorConfigurationLister {
	return v1beta1.NewFRROperatorConfigurationLister(f.Informer().GetIndexer())
}
