
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: frr-k8s
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: frr-k8s-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/part-of: frr-k8s
    app.kubernetes.io/managed-by: kustomize
  name: frr-k8s-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: metricshttps
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
    - path: /metrics
      port: frrmetricshttps
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: frr-k8s
