apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: frr-k8s-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/part-of: frr-k8s
    app.kubernetes.io/managed-by: kustomize
  name: nodestate-cleaner-role
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frrk8s.metallb.io
  resources:
  - frrnodestates
  verbs:
  - get
  - list
  - watch
  - delete
