apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: frr-k8s-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: frr-k8s
    app.kubernetes.io/part-of: frr-k8s
    app.kubernetes.io/managed-by: kustomize
  name: nodestate-cleaner-rolebinding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nodestate-cleaner-role
subjects:
- kind: ServiceAccount
  name: daemon
  namespace: system
