// SPDX-License-Identifier:Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// FRRConfigurationListerExpansion allows custom methods to be added to
// FRRConfigurationLister.
type FRRConfigurationListerExpansion interface{}

// FRRConfigurationNamespaceListerExpansion allows custom methods to be added to
// FRRConfigurationNamespaceLister.
type FRRConfigurationNamespaceListerExpansion interface{}

// FRROperatorConfigurationListerExpansion allows custom methods to be added to
// FRROperatorConfigurationLister.
type FRROperatorConfigurationListerExpansion interface{}

// FRROperatorConfigurationNamespaceListerExpansion allows custom methods to be added to
// FRROperatorConfigurationNamespaceLister.
type FRROperatorConfigurationNamespaceListerExpansion interface{}
