// SPDX-License-Identifier:Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

import (
	v1beta1 "github.com/metallb/frr-k8s/api/v1beta1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// FRROperatorConfigurationLister helps list FRROperatorConfigurations.
// All objects returned here must be treated as read-only.
type FRROperatorConfigurationLister interface {
	// List lists all FRROperatorConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.FRROperatorConfiguration, err error)
	// FRROperatorConfigurations returns an object that can list and get FRROperatorConfigurations.
	FRROperatorConfigurations(namespace string) FRROperatorConfigurationNamespaceLister
	FRROperatorConfigurationListerExpansion
}

// fRROperatorConfigurationLister implements the FRROperatorConfigurationLister interface.
type fRROperatorConfigurationLister struct {
	listers.ResourceIndexer[*v1beta1.FRROperatorConfiguration]
}

// NewFRROperatorConfigurationLister returns a new FRROperatorConfigurationLister.
func NewFRROperatorConfigurationLister(indexer cache.Indexer) FRROperatorConfigurationLister {
	return &fRROperatorConfigurationLister{listers.New[*v1beta1.FRROperatorConfiguration](indexer, v1beta1.Resource("frroperatorconfiguration"))}
}

// FRROperatorConfigurations returns an object that can list and get FRROperatorConfigurations.
func (s *fRROperatorConfigurationLister) FRROperatorConfigurations(namespace string) FRROperatorConfigurationNamespaceLister {
	return fRROperatorConfigurationNamespaceLister{listers.NewNamespaced[*v1beta1.FRROperatorConfiguration](s.ResourceIndexer, namespace)}
}

// FRROperatorConfigurationNamespaceLister helps list and get FRROperatorConfigurations.
// All objects returned here must be treated as read-only.
type FRROperatorConfigurationNamespaceLister interface {
	// List lists all FRROperatorConfigurations in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1beta1.FRROperatorConfiguration, err error)
	// Get retrieves the FRROperatorConfiguration from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1beta1.FRROperatorConfiguration, error)
	FRROperatorConfigurationNamespaceListerExpansion
}

// fRROperatorConfigurationNamespaceLister implements the FRROperatorConfigurationNamespaceLister
// interface.
type fRROperatorConfigurationNamespaceLister struct {
	listers.ResourceIndexer[*v1beta1.FRROperatorConfiguration]
}
