// SPDX-License-Identifier:Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"

	v1beta1 "github.com/metallb/frr-k8s/api/v1beta1"
	scheme "github.com/metallb/frr-k8s/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FRROperatorConfigurationsGetter has a method to return a FRROperatorConfigurationInterface.
// A group's client should implement this interface.
type FRROperatorConfigurationsGetter interface {
	FRROperatorConfigurations(namespace string) FRROperatorConfigurationInterface
}

// FRROperatorConfigurationInterface has methods to work with FRROperatorConfiguration resources.
type FRROperatorConfigurationInterface interface {
	Create(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.CreateOptions) (*v1beta1.FRROperatorConfiguration, error)
	Update(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.UpdateOptions) (*v1beta1.FRROperatorConfiguration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.UpdateOptions) (*v1beta1.FRROperatorConfiguration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.FRROperatorConfiguration, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.FRROperatorConfigurationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FRROperatorConfiguration, err error)
	FRROperatorConfigurationExpansion
}

// fRROperatorConfigurations implements FRROperatorConfigurationInterface
type fRROperatorConfigurations struct {
	*gentype.ClientWithList[*v1beta1.FRROperatorConfiguration, *v1beta1.FRROperatorConfigurationList]
}

// newFRROperatorConfigurations returns a FRROperatorConfigurations
func newFRROperatorConfigurations(c *ApiV1beta1Client, namespace string) *fRROperatorConfigurations {
	return &fRROperatorConfigurations{
		gentype.NewClientWithList[*v1beta1.FRROperatorConfiguration, *v1beta1.FRROperatorConfigurationList](
			"frroperatorconfigurations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1beta1.FRROperatorConfiguration { return &v1beta1.FRROperatorConfiguration{} },
			func() *v1beta1.FRROperatorConfigurationList { return &v1beta1.FRROperatorConfigurationList{} }),
	}
}
