//go:build !ignore_autogenerated

// SPDX-License-Identifier:Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Advertise) DeepCopyInto(out *Advertise) {
	*out = *in
	in.Allowed.DeepCopyInto(&out.Allowed)
	if in.PrefixesWithLocalPref != nil {
		in, out := &in.PrefixesWithLocalPref, &out.PrefixesWithLocalPref
		*out = make([]LocalPrefPrefixes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrefixesWithCommunity != nil {
		in, out := &in.PrefixesWithCommunity, &out.PrefixesWithCommunity
		*out = make([]CommunityPrefixes, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Advertise.
func (in *Advertise) DeepCopy() *Advertise {
	if in == nil {
		return nil
	}
	out := new(Advertise)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedInPrefixes) DeepCopyInto(out *AllowedInPrefixes) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]PrefixSelector, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedInPrefixes.
func (in *AllowedInPrefixes) DeepCopy() *AllowedInPrefixes {
	if in == nil {
		return nil
	}
	out := new(AllowedInPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllowedOutPrefixes) DeepCopyInto(out *AllowedOutPrefixes) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllowedOutPrefixes.
func (in *AllowedOutPrefixes) DeepCopy() *AllowedOutPrefixes {
	if in == nil {
		return nil
	}
	out := new(AllowedOutPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BFDProfile) DeepCopyInto(out *BFDProfile) {
	*out = *in
	if in.ReceiveInterval != nil {
		in, out := &in.ReceiveInterval, &out.ReceiveInterval
		*out = new(uint32)
		**out = **in
	}
	if in.TransmitInterval != nil {
		in, out := &in.TransmitInterval, &out.TransmitInterval
		*out = new(uint32)
		**out = **in
	}
	if in.DetectMultiplier != nil {
		in, out := &in.DetectMultiplier, &out.DetectMultiplier
		*out = new(uint32)
		**out = **in
	}
	if in.EchoInterval != nil {
		in, out := &in.EchoInterval, &out.EchoInterval
		*out = new(uint32)
		**out = **in
	}
	if in.EchoMode != nil {
		in, out := &in.EchoMode, &out.EchoMode
		*out = new(bool)
		**out = **in
	}
	if in.PassiveMode != nil {
		in, out := &in.PassiveMode, &out.PassiveMode
		*out = new(bool)
		**out = **in
	}
	if in.MinimumTTL != nil {
		in, out := &in.MinimumTTL, &out.MinimumTTL
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BFDProfile.
func (in *BFDProfile) DeepCopy() *BFDProfile {
	if in == nil {
		return nil
	}
	out := new(BFDProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfig) DeepCopyInto(out *BGPConfig) {
	*out = *in
	if in.Routers != nil {
		in, out := &in.Routers, &out.Routers
		*out = make([]Router, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BFDProfiles != nil {
		in, out := &in.BFDProfiles, &out.BFDProfiles
		*out = make([]BFDProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfig.
func (in *BGPConfig) DeepCopy() *BGPConfig {
	if in == nil {
		return nil
	}
	out := new(BGPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPSessionState) DeepCopyInto(out *BGPSessionState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPSessionState.
func (in *BGPSessionState) DeepCopy() *BGPSessionState {
	if in == nil {
		return nil
	}
	out := new(BGPSessionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPSessionState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPSessionStateList) DeepCopyInto(out *BGPSessionStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPSessionState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPSessionStateList.
func (in *BGPSessionStateList) DeepCopy() *BGPSessionStateList {
	if in == nil {
		return nil
	}
	out := new(BGPSessionStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPSessionStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPSessionStateSpec) DeepCopyInto(out *BGPSessionStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPSessionStateSpec.
func (in *BGPSessionStateSpec) DeepCopy() *BGPSessionStateSpec {
	if in == nil {
		return nil
	}
	out := new(BGPSessionStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPSessionStateStatus) DeepCopyInto(out *BGPSessionStateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPSessionStateStatus.
func (in *BGPSessionStateStatus) DeepCopy() *BGPSessionStateStatus {
	if in == nil {
		return nil
	}
	out := new(BGPSessionStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityPrefixes) DeepCopyInto(out *CommunityPrefixes) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityPrefixes.
func (in *CommunityPrefixes) DeepCopy() *CommunityPrefixes {
	if in == nil {
		return nil
	}
	out := new(CommunityPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EVPNConfig) DeepCopyInto(out *EVPNConfig) {
	*out = *in
	if in.AdvertiseVNIs != nil {
		in, out := &in.AdvertiseVNIs, &out.AdvertiseVNIs
		*out = new(VNIAdvertisement)
		**out = **in
	}
	if in.L2VNIs != nil {
		in, out := &in.L2VNIs, &out.L2VNIs
		*out = make([]L2VNI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.L3VNI != nil {
		in, out := &in.L3VNI, &out.L3VNI
		*out = new(L3VNI)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EVPNConfig.
func (in *EVPNConfig) DeepCopy() *EVPNConfig {
	if in == nil {
		return nil
	}
	out := new(EVPNConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRConfiguration) DeepCopyInto(out *FRRConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRConfiguration.
func (in *FRRConfiguration) DeepCopy() *FRRConfiguration {
	if in == nil {
		return nil
	}
	out := new(FRRConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRRConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRConfigurationList) DeepCopyInto(out *FRRConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FRRConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRConfigurationList.
func (in *FRRConfigurationList) DeepCopy() *FRRConfigurationList {
	if in == nil {
		return nil
	}
	out := new(FRRConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRRConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRConfigurationSpec) DeepCopyInto(out *FRRConfigurationSpec) {
	*out = *in
	in.BGP.DeepCopyInto(&out.BGP)
	out.Raw = in.Raw
	in.NodeSelector.DeepCopyInto(&out.NodeSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRConfigurationSpec.
func (in *FRRConfigurationSpec) DeepCopy() *FRRConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(FRRConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRConfigurationStatus) DeepCopyInto(out *FRRConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRConfigurationStatus.
func (in *FRRConfigurationStatus) DeepCopy() *FRRConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(FRRConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRNodeState) DeepCopyInto(out *FRRNodeState) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRNodeState.
func (in *FRRNodeState) DeepCopy() *FRRNodeState {
	if in == nil {
		return nil
	}
	out := new(FRRNodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRRNodeState) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRNodeStateList) DeepCopyInto(out *FRRNodeStateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FRRNodeState, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRNodeStateList.
func (in *FRRNodeStateList) DeepCopy() *FRRNodeStateList {
	if in == nil {
		return nil
	}
	out := new(FRRNodeStateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRRNodeStateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRNodeStateSpec) DeepCopyInto(out *FRRNodeStateSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRNodeStateSpec.
func (in *FRRNodeStateSpec) DeepCopy() *FRRNodeStateSpec {
	if in == nil {
		return nil
	}
	out := new(FRRNodeStateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRRNodeStateStatus) DeepCopyInto(out *FRRNodeStateStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRRNodeStateStatus.
func (in *FRRNodeStateStatus) DeepCopy() *FRRNodeStateStatus {
	if in == nil {
		return nil
	}
	out := new(FRRNodeStateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Import) DeepCopyInto(out *Import) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Import.
func (in *Import) DeepCopy() *Import {
	if in == nil {
		return nil
	}
	out := new(Import)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2VNI) DeepCopyInto(out *L2VNI) {
	*out = *in
	in.VNI.DeepCopyInto(&out.VNI)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2VNI.
func (in *L2VNI) DeepCopy() *L2VNI {
	if in == nil {
		return nil
	}
	out := new(L2VNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3VNI) DeepCopyInto(out *L3VNI) {
	*out = *in
	in.VNI.DeepCopyInto(&out.VNI)
	if in.AdvertisePrefixes != nil {
		in, out := &in.AdvertisePrefixes, &out.AdvertisePrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3VNI.
func (in *L3VNI) DeepCopy() *L3VNI {
	if in == nil {
		return nil
	}
	out := new(L3VNI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalPrefPrefixes) DeepCopyInto(out *LocalPrefPrefixes) {
	*out = *in
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalPrefPrefixes.
func (in *LocalPrefPrefixes) DeepCopy() *LocalPrefPrefixes {
	if in == nil {
		return nil
	}
	out := new(LocalPrefPrefixes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neighbor) DeepCopyInto(out *Neighbor) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(uint16)
		**out = **in
	}
	out.PasswordSecret = in.PasswordSecret
	if in.HoldTime != nil {
		in, out := &in.HoldTime, &out.HoldTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.KeepaliveTime != nil {
		in, out := &in.KeepaliveTime, &out.KeepaliveTime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ConnectTime != nil {
		in, out := &in.ConnectTime, &out.ConnectTime
		*out = new(v1.Duration)
		**out = **in
	}
	in.ToAdvertise.DeepCopyInto(&out.ToAdvertise)
	in.ToReceive.DeepCopyInto(&out.ToReceive)
	if in.AddressFamilies != nil {
		in, out := &in.AddressFamilies, &out.AddressFamilies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neighbor.
func (in *Neighbor) DeepCopy() *Neighbor {
	if in == nil {
		return nil
	}
	out := new(Neighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixSelector) DeepCopyInto(out *PrefixSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixSelector.
func (in *PrefixSelector) DeepCopy() *PrefixSelector {
	if in == nil {
		return nil
	}
	out := new(PrefixSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RawConfig) DeepCopyInto(out *RawConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RawConfig.
func (in *RawConfig) DeepCopy() *RawConfig {
	if in == nil {
		return nil
	}
	out := new(RawConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Receive) DeepCopyInto(out *Receive) {
	*out = *in
	in.Allowed.DeepCopyInto(&out.Allowed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Receive.
func (in *Receive) DeepCopy() *Receive {
	if in == nil {
		return nil
	}
	out := new(Receive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Router) DeepCopyInto(out *Router) {
	*out = *in
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]Neighbor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Imports != nil {
		in, out := &in.Imports, &out.Imports
		*out = make([]Import, len(*in))
		copy(*out, *in)
	}
	if in.EVPN != nil {
		in, out := &in.EVPN, &out.EVPN
		*out = new(EVPNConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Router.
func (in *Router) DeepCopy() *Router {
	if in == nil {
		return nil
	}
	out := new(Router)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VNI) DeepCopyInto(out *VNI) {
	*out = *in
	if in.ImportRTs != nil {
		in, out := &in.ImportRTs, &out.ImportRTs
		*out = make([]ImportRouteTarget, len(*in))
		copy(*out, *in)
	}
	if in.ExportRTs != nil {
		in, out := &in.ExportRTs, &out.ExportRTs
		*out = make([]ExportRouteTarget, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VNI.
func (in *VNI) DeepCopy() *VNI {
	if in == nil {
		return nil
	}
	out := new(VNI)
	in.DeepCopyInto(out)
	return out
}
