// SPDX-License-Identifier:Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/metallb/frr-k8s/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFRROperatorConfigurations implements FRROperatorConfigurationInterface
type FakeFRROperatorConfigurations struct {
	Fake *FakeApiV1beta1
	ns   string
}

var frroperatorconfigurationsResource = v1beta1.SchemeGroupVersion.WithResource("frroperatorconfigurations")

var frroperatorconfigurationsKind = v1beta1.SchemeGroupVersion.WithKind("FRROperatorConfiguration")

// Get takes name of the fRROperatorConfiguration, and returns the corresponding fRROperatorConfiguration object, and an error if there is any.
func (c *FakeFRROperatorConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FRROperatorConfiguration, err error) {
	emptyResult := &v1beta1.FRROperatorConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(frroperatorconfigurationsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRROperatorConfiguration), err
}

// List takes label and field selectors, and returns the list of FRROperatorConfigurations that match those selectors.
func (c *FakeFRROperatorConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FRROperatorConfigurationList, err error) {
	emptyResult := &v1beta1.FRROperatorConfigurationList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(frroperatorconfigurationsResource, frroperatorconfigurationsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FRROperatorConfigurationList{ListMeta: obj.(*v1beta1.FRROperatorConfigurationList).ListMeta}
	for _, item := range obj.(*v1beta1.FRROperatorConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fRROperatorConfigurations.
func (c *FakeFRROperatorConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(frroperatorconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a fRROperatorConfiguration and creates it.  Returns the server's representation of the fRROperatorConfiguration, and an error, if there is any.
func (c *FakeFRROperatorConfigurations) Create(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.CreateOptions) (result *v1beta1.FRROperatorConfiguration, err error) {
	emptyResult := &v1beta1.FRROperatorConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(frroperatorconfigurationsResource, c.ns, fRROperatorConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRROperatorConfiguration), err
}

// Update takes the representation of a fRROperatorConfiguration and updates it. Returns the server's representation of the fRROperatorConfiguration, and an error, if there is any.
func (c *FakeFRROperatorConfigurations) Update(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.UpdateOptions) (result *v1beta1.FRROperatorConfiguration, err error) {
	emptyResult := &v1beta1.FRROperatorConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(frroperatorconfigurationsResource, c.ns, fRROperatorConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRROperatorConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFRROperatorConfigurations) UpdateStatus(ctx context.Context, fRROperatorConfiguration *v1beta1.FRROperatorConfiguration, opts v1.UpdateOptions) (result *v1beta1.FRROperatorConfiguration, err error) {
	emptyResult := &v1beta1.FRROperatorConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(frroperatorconfigurationsResource, "status", c.ns, fRROperatorConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRROperatorConfiguration), err
}

// Delete takes name of the fRROperatorConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeFRROperatorConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(frroperatorconfigurationsResource, c.ns, name, opts), &v1beta1.FRROperatorConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFRROperatorConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(frroperatorconfigurationsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.FRROperatorConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched fRROperatorConfiguration.
func (c *FakeFRROperatorConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FRROperatorConfiguration, err error) {
	emptyResult := &v1beta1.FRROperatorConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(frroperatorconfigurationsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRROperatorConfiguration), err
}
