// SPDX-License-Identifier:Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/metallb/frr-k8s/api/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFRRK8sConfigurations implements FRRK8sConfigurationInterface
type FakeFRRK8sConfigurations struct {
	Fake *FakeApiV1beta1
	ns   string
}

var frrk8sconfigurationsResource = v1beta1.SchemeGroupVersion.WithResource("frrk8sconfigurations")

var frrk8sconfigurationsKind = v1beta1.SchemeGroupVersion.WithKind("FRRK8sConfiguration")

// Get takes name of the fRRK8sConfiguration, and returns the corresponding fRRK8sConfiguration object, and an error if there is any.
func (c *FakeFRRK8sConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.FRRK8sConfiguration, err error) {
	emptyResult := &v1beta1.FRRK8sConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(frrk8sconfigurationsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRRK8sConfiguration), err
}

// List takes label and field selectors, and returns the list of FRRK8sConfigurations that match those selectors.
func (c *FakeFRRK8sConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.FRRK8sConfigurationList, err error) {
	emptyResult := &v1beta1.FRRK8sConfigurationList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(frrk8sconfigurationsResource, frrk8sconfigurationsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.FRRK8sConfigurationList{ListMeta: obj.(*v1beta1.FRRK8sConfigurationList).ListMeta}
	for _, item := range obj.(*v1beta1.FRRK8sConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested fRRK8sConfigurations.
func (c *FakeFRRK8sConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(frrk8sconfigurationsResource, c.ns, opts))

}

// Create takes the representation of a fRRK8sConfiguration and creates it.  Returns the server's representation of the fRRK8sConfiguration, and an error, if there is any.
func (c *FakeFRRK8sConfigurations) Create(ctx context.Context, fRRK8sConfiguration *v1beta1.FRRK8sConfiguration, opts v1.CreateOptions) (result *v1beta1.FRRK8sConfiguration, err error) {
	emptyResult := &v1beta1.FRRK8sConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(frrk8sconfigurationsResource, c.ns, fRRK8sConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRRK8sConfiguration), err
}

// Update takes the representation of a fRRK8sConfiguration and updates it. Returns the server's representation of the fRRK8sConfiguration, and an error, if there is any.
func (c *FakeFRRK8sConfigurations) Update(ctx context.Context, fRRK8sConfiguration *v1beta1.FRRK8sConfiguration, opts v1.UpdateOptions) (result *v1beta1.FRRK8sConfiguration, err error) {
	emptyResult := &v1beta1.FRRK8sConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(frrk8sconfigurationsResource, c.ns, fRRK8sConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRRK8sConfiguration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFRRK8sConfigurations) UpdateStatus(ctx context.Context, fRRK8sConfiguration *v1beta1.FRRK8sConfiguration, opts v1.UpdateOptions) (result *v1beta1.FRRK8sConfiguration, err error) {
	emptyResult := &v1beta1.FRRK8sConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(frrk8sconfigurationsResource, "status", c.ns, fRRK8sConfiguration, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRRK8sConfiguration), err
}

// Delete takes name of the fRRK8sConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeFRRK8sConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(frrk8sconfigurationsResource, c.ns, name, opts), &v1beta1.FRRK8sConfiguration{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFRRK8sConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(frrk8sconfigurationsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.FRRK8sConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched fRRK8sConfiguration.
func (c *FakeFRRK8sConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.FRRK8sConfiguration, err error) {
	emptyResult := &v1beta1.FRRK8sConfiguration{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(frrk8sconfigurationsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1beta1.FRRK8sConfiguration), err
}
