name: Cancel
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-22.04
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
